In [89]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [73]:

result = pd.read_csv ("potencias_2018.csv", header=0);

In [74]:
result['data'] = pd.to_datetime (result['data'])
result = result.set_index(result.data)
data = result[['pa']]

In [97]:
resampled = data.resample('H').sum()
resampled['paVar'] = data.resample('H').var()

october = resampled['2018-10-10 00:00:00':'2018-10-12 23:00:00']

night = october.between_time('00:00:00', '06:00:00')
night

                             pa      paVar
data
2018-10-10 00:00:00  312.658265   0.972692
2018-10-10 01:00:00  302.919982   0.319675
2018-10-10 02:00:00  306.265381   1.458654
2018-10-10 03:00:00  302.461566   0.641025
2018-10-10 04:00:00  300.237151   0.352673
2018-10-10 05:00:00  316.160010   3.818322
2018-10-10 06:00:00  506.014487  90.980677
2018-10-11 00:00:00  329.638829   1.937183
2018-10-11 01:00:00  332.200879   1.126741
2018-10-11 02:00:00  331.712671   0.926452
2018-10-11 03:00:00  341.125790   1.150494
2018-10-11 04:00:00  313.609935   1.803534
2018-10-11 05:00:00  334.828284   3.994056
2018-10-11 06:00:00  464.911969  95.832473
2018-10-12 00:00:00  338.855520   0.377185
2018-10-12 01:00:00  291.573895   4.349771
2018-10-12 02:00:00  272.654127   0.424726
2018-10-12 03:00:00  273.730538   0.354746
2018-10-12 04:00:00  271.085581   0.635330
2018-10-12 05:00:00  255.823904   0.966156
2018-10-12 06:00:00  207.295305   0.388641